version: '3.1'

services:

  phpmyadmin:
   image: phpmyadmin/phpmyadmin:latest
   restart: always
   ports:
    - 8800:80
   links:
    - db
   environment:
    PMA_HOST: db
    PMA_PORT: 3306
    PMA_ARBITARY: 1
  
  db:
   image: mariadb:latest
   restart: always
   environment:
    MYSQL_ROOT_PASSWORD: redhat
   volumes:
    - db:/var/lib/mysql

volumes:
  db:
