version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 1235:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: vinayak
      WORDPRESS_DB_PASSWORD: redhat
      WORDPRESS_DB_NAME: wp
    volumes:
      - wordpress:/var/www/html

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: vinayak
      MYSQL_PASSWORD: redhat
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
